[package]
name = "transaction-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
csv = "*"
rust_decimal = { version = "*", features = ["serde-with-str"] }

[dev-dependencies]
rust_decimal_macros = "*"
